### ISSUE TITLE
Demo doesn't work

### ISSUE THREAD

**Issue by OKNoah** [AndreasMadsen/article#4]
Hey,

### Reproduce

1. Do steps 1-3 in the demo instructions.
1. Try to do `node tools/analyse/`

### Expected result

App should run

### Actual result

`Error: Cannot find module '/Users/User-Name/Documents/dev/modulebox/tools/analyse'`

There is no `tools` folder in the root folder, or any other folder I can see. The files in the folder are:

    LICENSE.md	README.md	lib		node_modules	package.json	test

**Comment by AndreasMadsen** [comment]
That is very odd. Clearly the `tools/analyse` folder is there (https://github.com/AndreasMadsen/article/tree/master/tools). Are you sure you are in the correct folder `modulebox` seams like the wrong name. Also I tried running the demo steps my self, it worked fine.

**Comment by OKNoah** [comment]
Hmm, I followed the instructions on the NPM site here: https://www.npmjs.com/package/article

**Comment by AndreasMadsen** [comment]
Oh, haha. That documentation is out of date. Thanks for posting the issue, I have updated the documentation on npm now.
